INSERT INTO hotels(id, name, description, city, rating) VALUES (1, 'Plaza Hotel', 'Hotel near Central Park', 'NYC', 5);
INSERT INTO hotels(id, name, description, city, rating) VALUES (2, 'Woodsprings', 'Hotel for cheap prices', 'Queens', 2);
INSERT INTO hotels(id, name, description, city, rating) VALUES (3, 'Holiday Inn', 'Live like you are at home', 'Cincinnati', 3);
INSERT INTO hotels(id, name, description, city, rating) VALUES (4, 'Journey B&B', 'Have some of our food in your room', 'Delhi', 3);
INSERT INTO hotels(id, name, description, city, rating) VALUES (5, 'La Quinta', 'Hotel for those road trip nights', 'San Francisco', 2);
INSERT INTO hotels(id, name, description, city, rating) VALUES (6, 'NJ INN', 'Hotel for NJers', 'Hoboken', 2);
INSERT INTO hotels(id, name, description, city, rating) VALUES (7, 'Taj Mahal Hotel and Casino', 'Hotel to sleep and gamble', 'Atlantic City', 4);
INSERT INTO hotels(id, name, description, city, rating) VALUES (8, 'Hotel Hugo', 'Hotel for the super classy', 'NYC', 4);
INSERT INTO hotels(id, name, description, city, rating) VALUES (9, 'Tropicana', 'Hotel to have fun and enjoy beach', 'Atlantic City', 4);
INSERT INTO hotels(id, name, description, city, rating) VALUES (10, 'Disney Hotel', 'Hotel for disney visiters', 'Orlando', 4);